---
- name: Test VMware collection
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Load VMware guest module
      community.vmware.vmware_guest:
        hostname: "192.168.0.195"
        username: "user"
        password: "pass"
        validate_certs: false
      register: vmware_test
      ignore_errors: true

    - name: Show VMware module result
      ansible.builtin.debug:
        var: vmware_test
