# This is a basic workflow that is manually triggered

name: Terraform Destroy workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  kueue-terraform-destroy:
    # The type of runner that the job will run on
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /mmfs1/data/scratch/runner/yd/terraform-provision
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: run hello
      run: echo "Hello ${{ inputs.name }}"
    - name: terraform destroy
      run: terraform destroy -auto-approve -input=false
